name: deploy-non-prd
on:
  push:
    branches:
      - dev
      - master
jobs:
  deploy-non-prd:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/bookinfo-ratings:$ENV_NAME
      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: k8s
          location: asia-southeast1-a
          credentials: ${{ secrets.GKE_CREDENTIALS }}
      - name: deploy
        uses: deliverybot/helm@v1
        with:
          helm: helm3
          release: bookinfo-$ENV_NAME-ratings
          namespace: student169-bookinfo-$ENV_NAME
          chart: k8s/helm
          value-files: k8s/helm-values/values-bookinfo-$ENV_NAME-ratings.yaml
          values: |
            COMMIT_SHA: $GITHUB_SHA
      - name: Test health check page
        run: curl http://bookinfo.$ENV_NAME.opsta.net/student169/ratings/health | grep 'Ratings is working'