name: deploy-non-prd
on:
  push:
    branches:
      - dev
      - master
jobs:
  deploy-non-prd:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && 'uat' || ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      - run: echo $ENV_NAME