name: dev-env

on:
  push:
    branches:
      - 'dev'

permissions:
  packages: write

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ghcr.io/winggundamth/bookinfo-ratings:dev .
      - run: docker images
      - run: docker push ghcr.io/winggundamth/bookinfo-ratings:dev