name: dev-env
on:
  push:
    branches:
      - 'dev'
jobs:
  build-push-docker-image:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ghcr.io/winggundamth/bookinfo-ratings:dev .
      - run: docker images
      - run: docker push ghcr.io/winggundamth/bookinfo-ratings:dev