name: tagging
on: 
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Version to tag'
        required: false
jobs:
  tagging:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Git tagging
        id: git-tag
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: ${{ github.event.inputs.tag_version }}
          DEFAULT_BUMP: patch
      - name: Docker tagging
        run: echo ${{ steps.git-tag.outputs.new_tag }}
